### PR TITLE
identify diego-ssh server to clients

### LINKED ISSUE #37: Identify the diego-ssh server via ServerVersion
# Background
diego-ssh/cmd/sshd identifies itself as `SSH-2.0-Go` which is the default value from the standard library. This prevents security scanning tools from properly identifying diego-ssh. 

This is important because the server identifies itself as accepting password authentication even though it's really a special OAuth flow which raises red flags for scanning tools. 

# How to verify
`$ ssh <diego-ssh> -vvv`

Look for:
```
debug1: Remote protocol version 2.0, remote software version Go
```

# Potential fix
Here's a patch I started but I'm having trouble getting everything to build. If you have a contributor guide I can take a crack at it or if you want to pick up this work that's great too.

```diff
diff --git a/cmd/sshd/main.go b/cmd/sshd/main.go
index 81286d0..ccd521c 100644
--- a/cmd/sshd/main.go
+++ b/cmd/sshd/main.go
@@ -182,7 +182,7 @@ func getDaemonEnvironment() map[string]string {
 
 func configure(logger lager.Logger) (*ssh.ServerConfig, error) {
 	errorStrings := []string{}
-	sshConfig := &ssh.ServerConfig{}
+	sshConfig := &ssh.ServerConfig{ServerVersion: "SSH-2.0-diego-ssh"}
 
 	key, err := acquireHostKey(logger)
 	if err != nil {
diff --git a/cmd/sshd/main_test.go b/cmd/sshd/main_test.go
index c823112..cbe7744 100644
--- a/cmd/sshd/main_test.go
+++ b/cmd/sshd/main_test.go
@@ -489,6 +489,12 @@ var _ = Describe("SSH daemon", func() {
 			client.Close()
 		})
 
+		Context("when a client connects", func() {
+			It("identifies itself as a diego-ssh server", func() {
+				Expect(client.Conn.ServerVersion()).To(Equal("SSH-2.0-diego-ssh"))
+			})
+		})
+
 		Context("when a client requests the execution of a command", func() {
 			It("runs the command", func() {
 				session, err := client.NewSession()
```

### PR DESCRIPTION
**Pull request by johnsonj**
fixes cloudfoundry/diego-ssh#37

### CODE REVIEW

**Comment by emalm** [comment]
Thanks, @johnsonj! Prioritizing for the Diego team to evaluate and pull in.

Best,
Eric

**Comment by bdshroyer** [comment]
Hi @johnsonj,

There are actually two binaries in diego-ssh that serve SSH traffic: sshd and ssh_proxy. Do they both need to identify themselves, and do they need to have separate identifiers (i.e., calling one `SSH-2.0-sshd` and the other `SSH-2.0-ssh_proxy`)?


Thanks,

@bdshroyer && @nimakaviani 

CF Diego Runtime

**Comment by johnsonj** [comment]
I'm tempted to say yes to identify them individually. They should
explicitly identify as Diego components, eg SSH-2.0-diego_ssh_proxy.

**Comment by johnsonj** [comment]
Thank you!

**Pull request merged**
